WITH ONLINE AS(
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    WHERE MONTH(SALES_DATE)=3 AND YEAR(SALES_DATE)=2022
),
OFFLINE AS(
    SELECT PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
    WHERE MONTH(SALES_DATE)=3 AND YEAR(SALES_DATE)=2022
)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
