WITH Available_Cars AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID 
    AND (
        (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
    )
    WHERE H.CAR_ID IS NULL
    AND C.CAR_TYPE IN ('세단', 'SUV')
),
Discounted_Fee AS (
    SELECT A.CAR_ID, A.CAR_TYPE, (A.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
    FROM Available_Cars A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON A.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, ROUND(FEE, 0)
FROM Discounted_Fee
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
