-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR AS FLAVOR
FROM ICECREAM_INFO, FIRST_HALF
WHERE FIRST_HALF.TOTAL_ORDER>3000 AND ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'
AND ICECREAM_INFO.FLAVOR=FIRST_HALF.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER DESC
